language: android
script:
  - ./gradlew assembleDebug
android:
  components:
  - build-tools-28.0.2
  - android-28
deploy:
  provider: releases
  api_key:
    secure: gw+yomXdfbHKcXl5AhLIy0RPccA3sA1+5q+TdsJRvMv8g0k6Qsdrx8lzMBAKdh790EbnbY8rI8JhoX4AazMwN66pV/EaOo5abVaHSORxEqYXMwim4YZPsOKeD0gGn7XRXQvoSsMqm5DJWnQtMKNXiqV1E4BT/8uua2BdmkL+kWE=
  file: ./build/outputs/apk/ComandoMEO-debug.apk
  on:
    tags: true
    repo: oNaiPs/ComandoMEO
